# Generated by Django 5.0 on 2023-12-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KamiaPlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planeid', models.IntegerField()),
                ('planename', models.CharField(max_length=180)),
                ('passengers', models.IntegerField()),
                ('tankcapacity', models.DecimalField(blank=True, decimal_places=4, max_digits=10)),
                ('fuelconsumption', models.DecimalField(blank=True, decimal_places=4, max_digits=10)),
                ('flyminutesVal', models.DecimalField(blank=True, decimal_places=4, max_digits=10)),
                ('flyminutes', models.CharField(blank=True, max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
